# Generated by Django 4.0.4 on 2022-04-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_superhero_delete_jeniskelamin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeniskelamin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jenis', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='superhero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
