# Generated by Django 4.0.4 on 2022-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_jeniskelamin_alter_superhero_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='jenis_kelamin',
            field=models.IntegerField(),
        ),
    ]
