# Generated by Django 4.0.4 on 2022-04-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_alter_superhero_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='superhero',
            table=None,
        ),
    ]
