# Generated by Django 4.0.4 on 2022-04-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_alter_superhero_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='jenis_kelamin',
            field=models.CharField(max_length=100),
        ),
    ]
