# Generated by Django 4.0.4 on 2022-04-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0007_alter_superhero_jenis_kelamin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillhero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
    ]
