# Generated by Django 4.0.4 on 2022-04-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0008_skillhero'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillhero',
            name='id_hero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='superhero',
            name='id_skills',
            field=models.IntegerField(null=True),
        ),
    ]
