# Generated by Django 4.0.4 on 2022-04-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0009_skillhero_id_hero_superhero_id_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hero', models.IntegerField(null=True)),
                ('id_skills', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skillhero',
            name='id_hero',
        ),
        migrations.RemoveField(
            model_name='superhero',
            name='id_skills',
        ),
    ]
